### ISSUE TITLE
lessHashed is not a function

### ISSUE THREAD

**Issue by ivandata** [ivandata/less-hashed#1]
`[23:44:21] Using gulpfile ~/gulpfile.js
[23:44:21] Starting 'default'...
[23:44:21] 'default' errored after 1.21 ms
[23:44:21] TypeError: lessHashed is not a function
    at Gulp.<anonymous> (/Users/malov/repo/test-less-hashed/gulpfile.js:21:16)
    at module.exports (/Users/malov/repo/test-less-hashed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/malov/repo/test-less-hashed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/malov/repo/test-less-hashed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/malov/repo/test-less-hashed/node_modules/orchestrator/index.js:134:8)
    at /Users/malov/.nvm/versions/node/v6.9.0/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)`

**Comment by ivandata** [comment]
solved
